import sys,re,os

regex = r"(SYS_\S+)\s+(\d+)"
pattern = re.compile(regex)
filename = sys.argv[1]
if __name__ == "__main__":
    print(f"# Generated by {os.path.split(__file__)[-1]}, don't edit this")
    print("# It's for aarch64 architecture\n")
    with open(filename,'r') as f:
        for line in f:
            ret = pattern.search(line)
            if not ret:
                continue
            call_name , call_num = ret.groups()
            print(f"# for {call_name}:{call_num}\n.global {call_name[4:]}")
            print(f"{call_name[4:]}:")
            print(f"\tmov\tx8, {call_num}")
            print("\tsvc\t0x0")
            print("\tret")
